apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: test-agent-cluster-install
  namespace: spoke-cluster
spec:
  apiVIP: 192.168.126.100
  apiVIPs:
    - 192.168.126.100
    - 1001:db8::10
  clusterDeploymentRef:
    name: test-cluster
  imageSetRef:
    name: openshift-v4.12
  ingressVIP: 192.168.126.103
  ingressVIPs:
    - 192.168.126.103
    - 1001:db8::11
  networking:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    - cidr: fd01::/48
      hostPrefix: 64
    machineNetwork:
    - cidr: 192.168.126.0/24
    - cidr: 1001:db8::/120
    serviceNetwork:
    - 172.30.0.0/16
    - fd02::/112
  provisionRequirements:
    controlPlaneAgents: 3
 #sshPublicKey: ssh-rsa your-public-key-here (optional)
  # By default, SMT (or hyperthreading) is enabled to increase the performance of your machines' cores.
  # Therefore, you can omit this section unless you wish to disable hyperthreading.
  # You can disable SMT by setting the parameter value to 'Disabled'. Then, you must disable it in all cluster machines;
  # this includes both control plane and compute machines.
  compute:
  - hyperthreading: Enabled
    name: worker
  controlPlane:
    hyperthreading: Enabled
    name: master
